<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Devall\Tabatadze\Model\CompanyRepository $block */
?>
<div class="block block-dashboard-company">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Company Information')) ?></strong>
        <a class="action edit" href="<?= $block->escapeUrl($block->getCompanyEditUrl()) ?>"><span><?= $block->escapeHtml(__('Change Associated Company')) ?></span></a>

    </div>
    <div class="block-content">
        <?php if ($block->hasCompany()) : ?>
            <div class="box">
                <strong class="box-title">
                    <span><?= $block->getName() ?></span>
                </strong>
                <div class="box-content">
                    <p>
                        <?= $block->getCountry() ?><br>
                        <?= $block->getStreet() ?><br>
                        <?= $block->getNumber() ?>
                    </p>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
