<?php

/** @var \Devall\Tabatadze\Model\CompanyRepository $block */
/** @var \Devall\Tabatadze\Block\CompanyList $block */

        $companies = $block->getCompanies();
?>
<form method="post" id="companyform" action="<?= $block->escapeUrl($block->getAction()) ?>" >
        <?= $block->getBlockHtml('formkey') ?>
            <select form="companyform" name="company" id="company">
                <?php foreach ($companies as $company): ?>
                    <option value="<?=$company->getId() ?>"  <?php if ($company->getId() == $block->compareCompany()): ?> selected <?php endif; ?>>
                        <?= $company->getName()?>
                    </option>
                <?php endforeach; ?>
            </select>
        <br>
        <br>
        <div class="primary">
            <button type="submit"
                    class="action save primary"
                    title="<?= $block->escapeHtmlAttr(__('Save Company')) ?>">
                <span><?= $block->escapeHtml(__('Save')) ?></span>
            </button>
        </div>
    </form>
